# Generated by Django 2.0.13 on 2019-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190425_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='caterogry',
            field=models.CharField(choices=[(1, 'Owoce'), (2, 'Warzywa'), (3, 'Mięso'), (4, 'Alkohol'), (5, 'Woda'), (6, 'Napoje słodkie'), (7, 'Przekąski słone'), (8, 'Słodycze'), (9, 'Elektronika'), (10, 'Akcesoria domowe'), (11, 'Usługi'), (12, 'Rozrywka')], default='Nieokreślony', max_length=100),
        ),
    ]
