# Generated by Django 2.0.13 on 2019-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190425_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='caterogry',
            field=models.IntegerField(choices=[(1, 'Owoce'), (2, 'Warzywa'), (3, 'Mięso'), (4, 'Alkohol'), (5, 'Woda'), (6, 'Napoje słodkie'), (7, 'Przekąski słone'), (8, 'Słodycze'), (9, 'Elektronika'), (10, 'Akcesoria domowe'), (11, 'Usługi'), (12, 'Rozrywka'), (13, 'Niokreslony')], default=13),
        ),
    ]
