# Generated by Django 2.0.13 on 2019-05-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190513_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
